spring.application.name=JPAapp

# configure data source properties
spring.datasource.url=jdbc:mysql://localhost:3306/hb-01-one-to-one-uni
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# hide the banner on running an app
spring.main.banner-mode=off

# change log level to warn and error
logging.level.root=warn